// pets.ts
import { Food, Outfit } from '../types/types';

const OUTFITS: Outfit[] = [
  // Hats
  {
    id: 'hat1',
    name: 'Black Cap',
    price: 500,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-hats/cap.png'), // Store/outfits menu image
    petImage: require('../../assets/images/clothes-on/clothes-on/hats-ON/cap-on.png'), // Pet display image
    type: 'hat',
  },
  {
    id: 'hat2',
    name: 'Shiesty',
    price: 1000,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-hats/shiesty-hat.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/hats-ON/shiesty-on.png'),
    type: 'hat',
  },
  {
    id: 'hat3',
    name: 'Sombrero',
    price: 700,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-hats/sombrero.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/hats-ON/sombrero-on.png'),
    type: 'hat',
  },
  {
    id: 'hat4',
    name: 'Spike Touque',
    price: 1500,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-hats/spike-hat.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/hats-ON/spike-hat-on.png'),
    type: 'hat',
  },
  {
    id: 'hat5',
    name: 'Touque',
    price: 700,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-hats/touque.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/hats-ON/touque-on.png'),
    type: 'hat',
  },
  {
    id: 'hat6',
    name: 'Ushanka',
    price: 1500,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-hats/ushanka.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/hats-ON/ushanka-on.png'),
    type: 'hat',
  },
  // Jackets
  {
    id: 'jacket1',
    name: 'Bubble Hoodie',
    price: 2500,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-jackets/badson-jacket.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/jackets-ON/badson-jacket-on.png'),
    type: 'jacket',
  },
  {
    id: 'jacket2',
    name: 'Carhartt Jacket',
    price: 3100,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-jackets/carhartt-jacket.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/jackets-ON/carhart-jacket-on.png'),
    type: 'jacket',
  },
  {
    id: 'jacket3',
    name: 'Dulse Hoodie',
    price: 3000,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-jackets/dulse-jacket.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/jackets-ON/dulse-jacket-on.png'),
    type: 'jacket',
  },
  {
    id: 'jacket4',
    name: 'Stipped Jacket',
    price: 3000,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-jackets/dulse1000-jacket.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/jackets-ON/dulse1000-jacket-on.png'),
    type: 'jacket',
  },
  {
    id: 'jacket5',
    name: 'Pet Hoodie',
    price: 2000,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-jackets/gap-jacket.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/jackets-ON/gap-jacket-on.png'),
    type: 'jacket',
  },
  {
    id: 'jacket6',
    name: 'Puffer Jacket',
    price: 3000,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-jackets/puffer-jacket.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/jackets-ON/puffer-jacket-on.png'),
    type: 'jacket',
  },
  // Shirts
  {
    id: 'shirt1',
    name: 'X Shirt',
    price: 800,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-shirts/badson-shirt.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/shirts-ON/badson-shirt-on.png'),
    type: 'shirt',
  },
  {
    id: 'shirt2',
    name: 'Bubble Shirt',
    price: 1500,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-shirts/buble-shirt.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/shirts-ON/bubble-shirt-on.png'),
    type: 'shirt',
  },
  {
    id: 'shirt3',
    name: 'Dressing Shirt',
    price: 900,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-shirts/dressing-shirt.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/shirts-ON/dressing-shirt-on.png'),
    type: 'shirt',
  },
  {
    id: 'shirt4',
    name: 'Dulse Shirt',
    price: 1500,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-shirts/dulse1000-shirt.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/shirts-ON/dulse1000-shirt-on.png'),
    type: 'shirt',
  },
  {
    id: 'shirt5',
    name: 'Muscle Shirt',
    price: 500,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-shirts/muscle-shirt.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/shirts-ON/muscle-shirt-on.png'),
    type: 'shirt',
  },
  {
    id: 'shirt6',
    name: 'Jersey',
    price: 1700,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-shirts/jersey-shirt.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/shirts-ON/jersey-shirt-on.png'),
    type: 'shirt',
  },
  // Pants
  {
    id: 'pants1',
    name: 'Badson Jeans',
    price: 3500,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-jeans/badson-jeans.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/jeans-ON/badson-jeans-on.png'),
    type: 'pants',
  },
  {
    id: 'pants2',
    name: 'Cargo Pants',
    price: 3000,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-jeans/cargo-pants.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/jeans-ON/cargo-pants-on.png'),
    type: 'pants',
  },
  {
    id: 'pants3',
    name: 'Dulse Jeans',
    price: 3700,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-jeans/dulse1000-jeans.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/jeans-ON/dulse1000-jeans-on.png'),
    type: 'pants',
  },
  {
    id: 'pants4',
    name: 'Cool Jeans',
    price: 3000,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-jeans/myjeans.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/jeans-ON/my-jeans-on.png'),
    type: 'pants',
  },
  {
    id: 'pants5',
    name: 'Stripped Jeans',
    price: 3200,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-jeans/stripped-jeans.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/jeans-ON/striped-jeans-on.png'),
    type: 'pants',
  },
  {
    id: 'pants6',
    name: 'Sweat Pants',
    price: 2100,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-jeans/sweat-pants.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/jeans-ON/sweat-pants-on.png'),
    type: 'pants',
  },
  // Shoes
  {
    id: 'shoes1',
    name: 'Dressing Shoes',
    price: 800,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-shoes/dressing-shoes.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/shoes-ON/dressing-shoes-on.png'),
    type: 'shoes',
  },
  {
    id: 'shoes2',
    name: 'Hulky Shoes',
    price: 1500,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-shoes/hulky-shoes.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/shoes-ON/hulky-shoes-on.png'),
    type: 'shoes',
  },
  {
    id: 'shoes3',
    name: 'NB Shoes',
    price: 1000,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-shoes/nb-shoes.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/shoes-ON/nb-shoes-on.png'),
    type: 'shoes',
  },
  {
    id: 'shoes4',
    name: 'Spike Shoes',
    price: 1200,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-shoes/spike-shoes.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/shoes-ON/spike-shoes-on.png'),
    type: 'shoes',
  },
  {
    id: 'shoes5',
    name: 'Timb Boots',
    price: 3000,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-shoes/timbs.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/shoes-ON/timbs-shoes-on.png'),
    type: 'shoes',
  },
  {
    id: 'shoes6',
    name: 'Ugly Shoes',
    price: 600,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-shoes/ugly-shoes.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/shoes-ON/ugly-shoes-on.png'),
    type: 'shoes',
  },
];

const FOODS: Food[] = [
  {
    id: 'food1',
    name: 'Apple',
    price: 15,
    owned: false,
    image: require('../../assets/images/clothes/clothes/foods/apple.png'),
    petImage: require('../../assets/images/clothes/clothes/foods/apple.png'),
    type: 'food',
    hungerRestore: 15
  },
  {
    id: 'food2',
    name: 'Pizza',
    price: 40,
    owned: false,
    image: require('../../assets/images/clothes/clothes/foods/pizza.png'),
    petImage: require('../../assets/images/clothes/clothes/foods/pizza.png'),
    type: 'food',
    hungerRestore: 40
  },
  {
    id: 'food3',
    name: 'Burger',
    price: 35,
    owned: false,
    image: require('../../assets/images/clothes/clothes/foods/burger.png'),
    petImage: require('../../assets/images/clothes/clothes/foods/burger.png'),
    type: 'food',
    hungerRestore: 35
  },
  {
    id: 'food4',
    name: 'Salad',
    price: 20,
    owned: false,
    image: require('../../assets/images/clothes/clothes/foods/salad.png'),
    petImage: require('../../assets/images/clothes/clothes/foods/salad.png'),
    type: 'food',
    hungerRestore: 20
  },
  {
    id: 'food5',
    name: 'Steak',
    price: 60,
    owned: false,
    image: require('../../assets/images/clothes/clothes/foods/steak.png'),
    petImage: require('../../assets/images/clothes/clothes/foods/steak.png'),
    type: 'food',
    hungerRestore: 60
  },
   {
    id: 'energy_potion_small',
    name: 'Small Energy Potion',
    price: 30,
    owned: false,
    image: require('../../assets/images/clothes/clothes/potions/small-potion.png'),
    petImage: require('../../assets/images/clothes/clothes/potions/small-potion.png'),
    type: 'food',
    hungerRestore: 0, // Doesn't affect hunger
    energyRestore: 20 // New property for energy restoration
  },
  {
    id: 'energy_potion_medium',
    name: 'Medium Energy Potion',
    price: 60,
    owned: false,
    image: require('../../assets/images/clothes/clothes/potions/medium-potion.png'),
    petImage: require('../../assets/images/clothes/clothes/potions/medium-potion.png'),
    type: 'food',
    hungerRestore: 0,
    energyRestore: 40
  },
  {
    id: 'energy_potion_large',
    name: 'Large Energy Potion',
    price: 100,
    owned: false,
    image: require('../../assets/images/clothes/clothes/potions/large-potion.png'),
    petImage: require('../../assets/images/clothes/clothes/potions/large-potion.png'),
    type: 'food',
    hungerRestore: 0,
    energyRestore: 70
  },
  {
    id: 'energy_potion_epic',
    name: 'Epic Energy Potion',
    price: 150,
    owned: false,
    image: require('../../assets/images/clothes/clothes/potions/legendary-potion.png'),
    petImage: require('../../assets/images/clothes/clothes/potions/legendary-potion.png'),
    type: 'food',
    hungerRestore: 0,
    energyRestore: 100
  }
];



export { FOODS, OUTFITS };

export default () => null;