// pets.ts
import { Food, Outfit } from '../types/types';

const OUTFITS: Outfit[] = [
  // Hats
  {
    id: 'hat1',
    name: 'Black Cap',
    price: 500,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-hats/cap.png'), // Store/outfits menu image
    petImage: require('../../assets/images/clothes-on/clothes-on/hats-ON/cap-on.png'), // Pet display image
    type: 'hat',
  },
  {
    id: 'hat2',
    name: 'Shiesty',
    price: 1000,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-hats/shiesty-hat.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/hats-ON/shiesty-on.png'),
    type: 'hat',
  },
  {
    id: 'hat3',
    name: 'Sombrero',
    price: 700,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-hats/sombrero.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/hats-ON/sombrero-on.png'),
    type: 'hat',
  },
  {
    id: 'hat4',
    name: 'Spike Touque',
    price: 1500,
    owned: false,
    image: require('../../assets/images/clothes/clothes/all-hats/spike-hat.png'),
    petImage: require('../../assets/images/clothes-on/clothes-on/hats-ON/spike-hat-on.png'),
    type: 'hat',
  },
  {
    id: 'hat5',
    name: 'Crown',
    price: 200,
    owned: false,
    image: require('../../assets/images/favicon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'hat',
  },
  // Jackets
  {
    id: 'jacket1',
    name: 'Denim Jacket',
    price: 150,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'jacket',
  },
  {
    id: 'jacket2',
    name: 'Leather Jacket',
    price: 250,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'jacket',
  },
  {
    id: 'jacket3',
    name: 'Hoodie',
    price: 120,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'jacket',
  },
  {
    id: 'jacket4',
    name: 'Bomber Jacket',
    price: 180,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'jacket',
  },
  {
    id: 'jacket5',
    name: 'Raincoat',
    price: 100,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'jacket',
  },
  // Shirts
  {
    id: 'shirt1',
    name: 'T-Shirt',
    price: 30,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'shirt',
  },
  {
    id: 'shirt2',
    name: 'Button-Up',
    price: 60,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'shirt',
  },
  {
    id: 'shirt3',
    name: 'Tank Top',
    price: 25,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'shirt',
  },
  {
    id: 'shirt4',
    name: 'Sweater',
    price: 80,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'shirt',
  },
  {
    id: 'shirt5',
    name: 'Polo',
    price: 50,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'shirt',
  },
  // Pants
  {
    id: 'pants1',
    name: 'Jeans',
    price: 100,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'pants',
  },
  {
    id: 'pants2',
    name: 'Shorts',
    price: 60,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'pants',
  },
  {
    id: 'pants3',
    name: 'Sweatpants',
    price: 70,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'pants',
  },
  {
    id: 'pants4',
    name: 'Cargo Pants',
    price: 90,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'pants',
  },
  {
    id: 'pants5',
    name: 'Dress Pants',
    price: 120,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'pants',
  },
  // Shoes
  {
    id: 'shoes1',
    name: 'Sneakers',
    price: 80,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'shoes',
  },
  {
    id: 'shoes2',
    name: 'Boots',
    price: 150,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'shoes',
  },
  {
    id: 'shoes3',
    name: 'Sandals',
    price: 50,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'shoes',
  },
  {
    id: 'shoes4',
    name: 'Dress Shoes',
    price: 120,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'shoes',
  },
  {
    id: 'shoes5',
    name: 'Flip Flops',
    price: 30,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'shoes',
  },
];

const FOODS: Food[] = [
  {
    id: 'food1',
    name: 'Apple',
    price: 10,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'food',
    hungerRestore: 15
  },
  {
    id: 'food2',
    name: 'Pizza',
    price: 30,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'food',
    hungerRestore: 40
  },
  {
    id: 'food3',
    name: 'Burger',
    price: 25,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'food',
    hungerRestore: 35
  },
  {
    id: 'food4',
    name: 'Salad',
    price: 15,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'food',
    hungerRestore: 20
  },
  {
    id: 'food5',
    name: 'Steak',
    price: 50,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'food',
    hungerRestore: 60
  },
   {
    id: 'energy_potion_small',
    name: 'Small Energy Potion',
    price: 30,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'food',
    hungerRestore: 0, // Doesn't affect hunger
    energyRestore: 20 // New property for energy restoration
  },
  {
    id: 'energy_potion_medium',
    name: 'Medium Energy Potion',
    price: 60,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'food',
    hungerRestore: 0,
    energyRestore: 40
  },
  {
    id: 'energy_potion_large',
    name: 'Large Energy Potion',
    price: 100,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'food',
    hungerRestore: 0,
    energyRestore: 70
  },
  {
    id: 'energy_potion_epic',
    name: 'Epic Energy Potion',
    price: 150,
    owned: false,
    image: require('../../assets/images/adaptive-icon.png'),
    petImage: require('../../assets/images/galaxy.gif'),
    type: 'food',
    hungerRestore: 0,
    energyRestore: 100
  }
];



export { FOODS, OUTFITS };

export default () => null;